name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Loteria client app image
        run: docker build -t client-build ./client

      - name: Package build for Elastic Beanstalk
        run: zip -r ${{ github.run_id }}.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-697697503646
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: ${{ github.run_id }}.zip